name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang llvm lld gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu bc flex bison make python3 libssl-dev

      - name: Set up environment variables
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=clang

      - name: Create output directory
        run: |
          mkdir -p out

      - name: Run defconfig
        run: |
          make O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- RMX3265_defconfig

      - name: Compile kernel
        run: |
          make O=out ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc)

      - name: Upload compiled kernel
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: out/arch/arm64/boot/Image.gz-dtb
